from tkinter import ttk
from tkinter import *
from PIL import ImageTk, Image
import tkinter
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure
import numpy as np


def unidesMinimasOP():
    subfondo2.place(x=570, y=340)
    subfondo25 =  Label(raiz, bg='gray', width=75, height=20)
    subfondo25.place(x=720, y=370)

    precio = float(precioDeVenta.get())
    costoVariable = float(costoUnitario.get())
    costosFijos = float(gastosFijosMensuales.get())
    margenDeContribucion = precio - costoVariable
    unidadesMinimas = costosFijos / margenDeContribucion
    label3.configure(text=f"{unidadesMinimas:.2f}")  # Redondea a 2 decimales

    equilibrio = costosFijos / (margenDeContribucion / precio)
    label4.configure(text=f"Q {equilibrio:.2f}")  # Redondea a 2 decimales

    boton2.configure(text='Datos graficados',bg="#970CFB",fg="white", width=17, relief="ridge",)
    subfondo3.place_forget()
    subfondo4.place_forget()
    datos1.place_forget()
    datos2.place_forget()
    datos3.place_forget()
    datos4.place_forget()
    datos5.place_forget()
    datos6.place_forget()
    datos7.place_forget()

    menos1.place_forget()
    menos2.place_forget()
    menos3.place_forget()
    menos4.place_forget()
    menos5.place_forget()
    menos6.place_forget()
    menos7.place_forget()
    menos2.configure(text=int(unidadesMinimas-(unidadesMinimas*0.25)))
    menos3.configure(text="Q "+ str(equilibrio-(equilibrio*0.25)))
    menos4.configure(text="Q "+ str((unidadesMinimas*costoVariable)-(unidadesMinimas*costoVariable*0.25)))
    menos5.configure(text="Q "+ str(costosFijos))
    menos6.configure(text="Q "+ str((unidadesMinimas*costoVariable)-(unidadesMinimas*costoVariable*0.25)+costosFijos))
    menos7.configure(text="Q "+ str((equilibrio-(equilibrio*0.25))-((unidadesMinimas*costoVariable)-(unidadesMinimas*costoVariable*0.25)+costosFijos)))

    normal1.place_forget()
    normal2.place_forget()
    normal3.place_forget()
    normal4.place_forget()
    normal5.place_forget()
    normal6.place_forget()
    normal7.place_forget()
    normal2.configure(text=int(unidadesMinimas))
    normal3.configure(text="Q "+ str(equilibrio))
    normal4.configure(text="Q "+ str(unidadesMinimas*costoVariable))
    normal5.configure(text="Q "+ str(costosFijos))
    normal6.configure(text="Q "+ str(costosFijos+(unidadesMinimas*costoVariable)))
    normal7.configure(text="Q "+ str(equilibrio-(costosFijos+(unidadesMinimas*costoVariable))))

    mas1.place_forget()
    mas2.place_forget()
    mas3.place_forget()
    mas4.place_forget()
    mas5.place_forget()
    mas6.place_forget()
    mas7.place_forget()
    mas2.configure(text=int(unidadesMinimas+(unidadesMinimas*0.25)))
    mas3.configure(text="Q "+ str(equilibrio+(equilibrio*0.25)))
    mas4.configure(text="Q "+ str((unidadesMinimas*costoVariable)+(unidadesMinimas*costoVariable*0.25)))
    mas5.configure(text="Q "+ str(costosFijos))
    mas6.configure(text="Q "+ str((unidadesMinimas*costoVariable)+(unidadesMinimas*costoVariable*0.25)+costosFijos))
    mas7.configure(text="Q "+ str((equilibrio+(equilibrio*0.25))-((unidadesMinimas*costoVariable)+(unidadesMinimas*costoVariable*0.25)+costosFijos)))

    CF= (unidadesMinimas*costoVariable)+(unidadesMinimas*costoVariable*0.25)
    U= unidadesMinimas+(unidadesMinimas*0.25)
    IT = equilibrio+(equilibrio*0.25)
    CV = costoVariable*U
    CT = (unidadesMinimas*costoVariable)+(unidadesMinimas*costoVariable*0.25)+costosFijos

    fig = Figure(figsize=(6, 3.6), dpi=76)
    t = np.arange(0, 1, .01)
    fig.add_subplot(111).plot(U*t,IT*t, U*t,CV*t, [0,unidadesMinimas,unidadesMinimas],[equilibrio,equilibrio,0],[0,U],[costosFijos,costosFijos],[0,U],[costosFijos,CT])
    canvas = FigureCanvasTkAgg(fig, master=subfondo25)
    canvas.draw()
    canvas.get_tk_widget().pack(expand=1)

    cubito1.place(x=590, y=400)
    cubito2.place(x=590, y=450)
    cubito3.place(x=590, y=500)
    cubito4.place(x=590, y=550)
    cubito5.place(x=590, y=600)

    color1.place(x=610, y=400)
    color2.place(x=610, y=450)
    color3.place(x=610, y=500)
    color4.place(x=610, y=550)
    color5.place(x=610, y=600)

    
def mostrarDatosGraficados():
    subfondo25.destroy()
    boton2.configure(text='Datos graficados',bg="#EBE6EF",fg="black", width=17, relief="ridge",)
    subfondo3.place(x=75, y=390)
    subfondo4.place(x=82, y=397)

    datos1.place(x=90, y=410)
    datos2.place(x=90, y=440)
    datos3.place(x=90, y=470)
    datos4.place(x=90, y=500)
    datos5.place(x=90, y=530)
    datos6.place(x=90, y=560)
    datos7.place(x=90, y=590)

    menos1.place(x=240, y=410)
    menos2.place(x=240, y=440)
    menos3.place(x=240, y=470)
    menos4.place(x=240, y=500)
    menos5.place(x=240, y=530)
    menos6.place(x=240, y=560)
    menos7.place(x=240, y=590)

    normal1.place(x=330, y=410)
    normal2.place(x=330, y=440)
    normal3.place(x=330, y=470)
    normal4.place(x=330, y=500)
    normal5.place(x=330, y=530)
    normal6.place(x=330, y=560)
    normal7.place(x=330, y=590)

    mas1.place(x=420, y=410)
    mas2.place(x=420, y=440)
    mas3.place(x=420, y=470)
    mas4.place(x=420, y=500)
    mas5.place(x=420, y=530)
    mas6.place(x=420, y=560)
    mas7.place(x=420, y=590)


raiz=Tk()
raiz.title('   Proyecto Final')
raiz.iconbitmap('icoso.ico')
raiz.geometry('1280x754')
raiz.resizable(0, 0)
raiz.config(bg='#BC0970')

# Carga una imagen como fondo
imagen_fondo = ImageTk.PhotoImage(Image.open("count.jpg"))

# Crea una etiqueta para mostrar la imagen como fondo
fondo_label = Label(raiz, image=imagen_fondo)
fondo_label.place(x=0, y=12, relwidth=1, relheight=1)

label1 = Label(raiz,text='PROYECTO FINAL CONTABILIDAD II', bg="black", fg="white", border=12)
label1.configure(font=("Consolas", 16, "roman"))
label1.place(x=0, y=0)

miNombre0 = Label(raiz,text='Lic. Antonio Maldonado', bg="black", fg="white", border=12)
miNombre0.configure(font=("Consolas", 16, "roman"))
miNombre0.place(x=25, y=700)

miNombre = Label(raiz, text='Kevin Josué Gutierrez Linares\nCarnet: 0907-23-1166', bg='black', fg='white',border=4)
miNombre.configure(font=("Consolas", 10, "roman"))
miNombre.place(x=825, y=0)

miNombre2 = Label(raiz, text='Angélica María Mejía Tzoc\nCarnet: 0907-23-8872', bg='black', fg='white',border=4)
miNombre2.configure(font=("Consolas", 10, "roman"))
miNombre2.place(x=1075, y=0) 

subfondo =  Label(raiz, bg='white', width= 120, height=17)
subfondo.place(x=67, y=110)

subfondo2 =  Label(raiz, bg='#2E2B20', width= 75, height=22)
subfondo2.place_forget()

subfondo25 =  Label(raiz, bg='gray', width= 55, height=18)
subfondo25.place(x=720, y=370)
subfondo25.place_forget()

labelP = Label(raiz,text='Punto de equilibrio', bg="black", fg="white", border=10)
labelP.configure(font=("Consolas", 16, "bold"))
labelP.place(x=100, y=90)

label21 = Label(raiz,text='Precio de venta', bg="white", border=10)
label21.configure(font=("Consolas", 12, "bold"))
label21.place(x=95, y=140)
label22 = Label(raiz,text='Costo unitario', bg="white", border=10)
label22.configure(font=("Consolas", 12, "bold"))
label22.place(x=95, y=170)
label23 = Label(raiz,text='Gastos Fijos Mensuales', bg="white", border=10)
label23.configure(font=("Consolas", 12, "bold"))
label23.place(x=95, y=200)
label24 = Label(raiz,text='Unidades minimas', bg="white", border=10)
label24.configure(font=("Consolas", 12, "bold"))
label24.place(x=95, y=240)
label25 = Label(raiz,text='Cantidad nesesaria \npara el equilibrio', bg="white", border=10)
label25.configure(font=("Consolas", 12, "bold"))
label25.place(x=95, y=280)

precioDeVenta = Entry(raiz, width = 27, border=1.5, relief="ridge")
precioDeVenta.configure(font=("Consolas", 12, "bold"))
precioDeVenta.place(x=350,y=150)
costoUnitario = Entry(raiz, width = 27, border=1.5, relief="ridge")
costoUnitario.configure(font=("Consolas", 12, "bold"))
costoUnitario.place(x=350,y=180)
gastosFijosMensuales = Entry(raiz, width = 27, border=1.5, relief="ridge")
gastosFijosMensuales.configure(font=("Consolas", 12, "bold"))
gastosFijosMensuales.place(x=350,y=210)
label3 = Label(raiz,text='------------', bg="white", border=10)
label3.configure(font=("Consolas", 12, "bold"))
label3.place(x=340, y=240)
label4 = Label(raiz,text='  ------------', bg="white", border=10)
label4.configure(font=("Consolas", 12, "bold"))
label4.place(x=323, y=290)

boton1 = Button(raiz,text='Punto de equilibrio',bg="#0D36EF",fg="white",command=unidesMinimasOP, width=20, relief="ridge")
boton1.configure(font=("Consolas", 12, "bold"))
boton1.place(x=640,y=220)
precioDeVenta.focus()

boton2 = Button(raiz,text='Datos graficados',bg="#0D36EF",fg="white", width=20, relief="ridge", command=mostrarDatosGraficados)
boton2.configure(font=("Consolas", 12, "bold"))
boton2.place(x=110,y=360)

subfondo3 =  Label(raiz, bg='#1a5ac9', width= 67, height=17)
subfondo3.place_forget()
subfondo4 =  Label(raiz, bg='#EBE6EF', width= 65, height=16)
subfondo4.place_forget()

datos1 = Label(raiz,text='', bg="#EBE6EF", border=10)
datos1.configure(font=("Consolas", 11, "normal"))
datos1.place_forget()
datos2 = Label(raiz,text='Numero de Unidades', bg="#EBE6EF", border=10)
datos2.configure(font=("Consolas", 8, "normal"))
datos2.place_forget()
datos3 = Label(raiz,text='Ingreso por Venta', bg="#EBE6EF", border=10)
datos3.configure(font=("Consolas", 8, "normal"))
datos3.place_forget()
datos4 = Label(raiz,text='Costos Variables', bg="#EBE6EF", border=10)
datos4.configure(font=("Consolas", 8, "normal"))
datos4.place_forget()
datos5 = Label(raiz,text='Costos Fijos', bg="#EBE6EF", border=10)
datos5.configure(font=("Consolas", 8, "normal"))
datos5.place_forget()
datos6 = Label(raiz,text='Costos Totales', bg="#EBE6EF", border=10)
datos6.configure(font=("Consolas", 8, "normal"))
datos6.place_forget()
datos7 = Label(raiz,text='Resultado', bg="#EBE6EF", border=10)
datos7.configure(font=("Consolas", 8, "normal"))
datos7.place_forget()

menos1 = Label(raiz,text='25% menos', bg="#EBE6EF", border=10)
menos1.configure(font=("Consolas", 8, "normal"))
menos1.place_forget()
menos2 = Label(raiz,text='', bg="#EBE6EF", border=10)
menos2.configure(font=("Consolas", 8, "normal"))
menos2.place_forget()
menos3 = Label(raiz,text='', bg="#EBE6EF", border=10)
menos3.configure(font=("Consolas", 8, "normal"))
menos3.place_forget()
menos4 = Label(raiz,text='', bg="#EBE6EF", border=10)
menos4.configure(font=("Consolas", 8, "normal"))
menos4.place_forget()
menos5 = Label(raiz,text='', bg="#EBE6EF", border=10)
menos5.configure(font=("Consolas", 8, "normal"))
menos5.place_forget()
menos6 = Label(raiz,text='', bg="#EBE6EF", border=10)
menos6.configure(font=("Consolas", 8, "normal"))
menos6.place_forget()
menos7 = Label(raiz,text='', bg="#EBE6EF", border=10)
menos7.configure(font=("Consolas", 8, "normal"))
menos7.place_forget()

normal1 = Label(raiz,text='Equilibrio', bg="#EBE6EF", border=10)
normal1.configure(font=("Consolas", 8, "normal"))
normal1.place_forget()
normal2 = Label(raiz,text='', bg="#EBE6EF", border=10)
normal2.configure(font=("Consolas", 8, "normal"))
normal2.place_forget()
normal3 = Label(raiz,text='', bg="#EBE6EF", border=10)
normal3.configure(font=("Consolas", 8, "normal"))
normal3.place_forget()
normal4 = Label(raiz,text='', bg="#EBE6EF", border=10)
normal4.configure(font=("Consolas", 8, "normal"))
normal4.place_forget()
normal5 = Label(raiz,text='', bg="#EBE6EF", border=10)
normal5.configure(font=("Consolas", 8, "normal"))
normal5.place_forget()
normal6 = Label(raiz,text='', bg="#EBE6EF", border=10)
normal6.configure(font=("Consolas", 8, "normal"))
normal6.place_forget()
normal7 = Label(raiz,text='', bg="#EBE6EF", border=10)
normal7.configure(font=("Consolas", 8, "normal"))
normal7.place_forget()

mas1 = Label(raiz,text='  25% mas', bg="#EBE6EF", border=10)
mas1.configure(font=("Consolas", 8, "normal"))
mas1.place_forget()
mas2 = Label(raiz,text='', bg="#EBE6EF", border=10)
mas2.configure(font=("Consolas", 8, "normal"))
mas2.place_forget()
mas3 = Label(raiz,text='', bg="#EBE6EF", border=10)
mas3.configure(font=("Consolas", 8, "normal"))
mas3.place_forget()
mas4 = Label(raiz,text='', bg="#EBE6EF", border=10)
mas4.configure(font=("Consolas", 8, "normal"))
mas4.place_forget()
mas5 = Label(raiz,text='', bg="#EBE6EF", border=10)
mas5.configure(font=("Consolas", 8, "normal"))
mas5.place_forget()
mas6 = Label(raiz,text='', bg="#EBE6EF", border=10)
mas6.configure(font=("Consolas", 8, "normal"))
mas6.place_forget()
mas7 = Label(raiz,text='', bg="#EBE6EF", border=10)
mas7.configure(font=("Consolas", 8, "normal"))
mas7.place_forget()

cubito1= Label(raiz, bg='red', width= 2, height=1)
cubito1.place_forget()
cubito2= Label(raiz, bg='blue', width= 2, height=1)
cubito2.place_forget()
cubito3= Label(raiz, bg='green', width= 2, height=1)
cubito3.place_forget()
cubito4= Label(raiz, bg='orange', width= 2, height=1)
cubito4.place_forget()
cubito5= Label(raiz, bg='purple', width= 2, height=1)
cubito5.place_forget()

color1= Label(raiz,text='Costos fijos', bg="#9C4513", fg="white")
color1.configure(font=("Consolas", 9, "normal"))
color1.place_forget()
color2= Label(raiz,text='Ingreso total', bg="#9C4513", fg="white")
color2.configure(font=("Consolas", 9, "normal"))
color2.place_forget()
color3= Label(raiz,text='Equilibrio', bg="#9C4513",  fg="white")
color3.configure(font=("Consolas", 9, "normal"))
color3.place_forget()
color4= Label(raiz,text='Costo Variable', bg="#9C4513",  fg="white")
color4.configure(font=("Consolas", 9, "normal"))
color4.place_forget()
color5= Label(raiz,text='Costos totales', bg="#9C4513",  fg="white")
color5.configure(font=("Consolas", 9, "normal"))
color5.place_forget()

raiz.mainloop()